spring.application.name=onlineshopping
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/OOPassik3
spring.datasource.username=postgres
spring.datasource.password=assel09@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true